apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: hello-world
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
        - image: asia.gcr.io/wdpress-173204/wdpress/hello-world
          imagePullPolicy: Always
          name: hello-world

