apiVersion: v1
kind: Service
metadata:
  name: lb-makkie
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    pod_id: makkie
