apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-makkie
spec:
  replicas: 2
  selector:
    pod_id: makkie
  template:
    metadata:
      labels:
        pod_id: makkie
    spec:
      containers:
        - name: nginx-container
          image: zembutsu/docker-sample-nginx:1.0
          ports:
            - containerPort: 80
